# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareback_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacks',
            name='comment',
            field=models.TextField(db_column='comment', null=True),
        ),
        migrations.AddField(
            model_name='sessionfiles',
            name='file',
            field=models.TextField(db_column='file', null=True),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='rating_1',
            field=models.IntegerField(db_column='rating_1'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='rating_2',
            field=models.IntegerField(db_column='rating_2'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='rating_3',
            field=models.IntegerField(db_column='rating_3'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='rating_4',
            field=models.IntegerField(db_column='rating_4'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='rating_5',
            field=models.IntegerField(db_column='rating_5'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='session_id',
            field=models.CharField(db_column='session_id', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='session_name',
            field=models.CharField(db_column='session_name', max_length=120),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='timestamp',
            field=models.DateField(auto_now=True, db_column='timestamp'),
        ),
    ]
