class Constants:
    SESSION_NAME = "session_name"
    USERNAME = "username"
    SESSION_ID = "session_id"
    FILE_NAME_ARRAY = "file_name"
    FILE_PATH_ARRAY = "file_path"
    FILE_PATH = "file_path"
    RATING = "rating"
    COMMENT = "comment"
    DESTINATION_PATH = "dest_path"
    DIR_NAME_ARRAY = "dir_name"
    DIRECTORY_PATH = "dir_path"
    DIRECTORY_PATH_ARR = "dir_path"
    OLD_FILE_PATH = "old_path"
    NEW_FILE_PATH = "new_path"
    REQUEST_NO = "request_no"
    PASSWORD = "password"
    FIRST_NAME = "fname"
    LAST_NAME = "lname"
    EMAIL = "email"
    FILE_PATH = "file_path"
    NEW_NAME = "new_name"

    FILE_TO_UPLOAD = "ufile"
